on: [workflow_dispatch]

name: 'terraform'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    

     # Install the latest version of Terraform CLI and 
     #configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
        cli_config_credentials_hostname: app.terraform.io
        terraform_version: 1.2.2
    

    
